name: test-branch-name
on:
  push:
    branches: 
      - main
jobs:
  get_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo $GIT_BRANCH
          echo "Testing"
      
      
